{
 "title": "Viessmann",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Outside temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "outdoor_temp" }
   ]
  },
  {
   "title": "Room Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "raum_ist_temp" }
   ]
  },
  {
   "title": "Water Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ww_ist_temp" }
   ]
  },
  {
   "title": "Operating Mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mode" }
   ]
  },
  {
   "title": "Circulation Pump",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Concentration" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "circ_pomp" }
   ]
  },
  {
   "title": "Number of Ignition",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "starts" }
   ]
  },
  {
   "title": "Circulation Pump",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Concentration" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "H_pomp" }
   ]
  },
  {
   "title": "Stove Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "k_ist_temp" }
   ]
  },
  {
   "title": "Burn/Return Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "k_abgas_temp", "legendFormat": "Return" }
   ]
  },
  {
   "title": "Gas Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "power" }
   ]
  },
  {
   "title": "Economic & Part Mode",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "saving", "legendFormat": "Economy Mode" },
    { "expr": "party", "legendFormat": "Part Mode" }
   ]
  },
  {
   "title": "Water Heating Pump",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Concentration" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "WW_pomp" }
   ]
  },
  {
   "title": "Run Time Hours",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "runtime_h" }
   ]
  },
  {
   "title": "Outside temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "outdoor_temp" }
   ]
  },
  {
   "title": "Room Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "raum_ist_temp", "legendFormat": "Room Temperature" },
    { "expr": "raum_soll_temp", "legendFormat": "Room Target" },
    { "expr": "red_raum_soll_temp", "legendFormat": "Night Temperature" }
   ]
  },
  {
   "title": "Gas Power - Historical",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "power", "legendFormat": "Moc Palnika" },
    { "expr": "k_ist_temp", "legendFormat": "Temperatura Kotła" },
    { "expr": "ww_ist_temp", "legendFormat": "Temperatura Wody" },
    { "expr": "k_abgas_temp", "legendFormat": "Temperatura Powrót/Spalin" }
   ]
  }
 ]
}